CREATE OR ALTER   PROCEDURE spDeleteAuthor
    @AuthorId UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

BEGIN TRANSACTION;

BEGIN TRY
DELETE FROM Blogs
WHERE AuthorId = @AuthorId;

DELETE FROM Authors
WHERE AuthorId = @AuthorId;

COMMIT TRANSACTION;
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION;
        THROW;
END CATCH
END;